### ISSUE TITLE
如何忽略PHPstorm的警告并加上代码提示呢

### ISSUE THREAD

**Issue by akmumu** [bukka/php-jsond#12]
![image](https://cloud.githubusercontent.com/assets/3242526/9575939/1def1ad2-5006-11e5-8181-aafca14cdddf.png)

**Comment by bukka** [comment]
That's correct if it's a master branch. It automatically replaces the json ext functions so if you use json_decode, then it uses jsond ... There also is an option how to use jsond prefix instead if you compile it with `--enable-jsond-prefixing`.

I should update the documentation. I plan to do it before releasing 1.4 so I'll leave it open and close it once the doc is updated.

**Comment by akmumu** [comment]
thanks and waiting for you @bukka

**Comment by Alexdener** [comment]
thanks @bukka

**Comment by bukka** [comment]
It's back to `jsond` and there is an option to use `json` prefix if required
