### ISSUE TITLE
Do not support to PHP7?

### ISSUE THREAD

**Issue by jixiaod** [bukka/php-jsond#15]
tiger➜php-7.0.7/ext/php-jsond(next✗)» make                                                                                                        [11:14:27]
/bin/sh /opt/package/php-7.0.7/ext/php-jsond/libtool --mode=compile cc  -I. -I/opt/package/php-7.0.7/ext/php-jsond -DPHP_ATOM_INC -I/opt/package/php-7.0.7/ext/php-jsond/include -I/opt/package/php-7.0.7/ext/php-jsond/main -I/opt/package/php-7.0.7/ext/php-jsond -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/package/php-7.0.7/ext/php-jsond/jsond.c -o jsond.lo 
mkdir .libs
 cc -I. -I/opt/package/php-7.0.7/ext/php-jsond -DPHP_ATOM_INC -I/opt/package/php-7.0.7/ext/php-jsond/include -I/opt/package/php-7.0.7/ext/php-jsond/main -I/opt/package/php-7.0.7/ext/php-jsond -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/package/php-7.0.7/ext/php-jsond/jsond.c  -fno-common -DPIC -o .libs/jsond.o
In file included from /opt/package/php-7.0.7/ext/php-jsond/jsond.c:25:
./php_jsond.h:36:10: fatal error: 'phpc/phpc.h' file not found
# include "phpc/phpc.h"

```
     ^
```

1 error generated.
make: **\* [jsond.lo] Error 1

**Comment by bukka** [comment]
slowly working on it: https://github.com/bukka/php-jsond/tree/next

**Comment by bukka** [comment]
It's still not compile as I'm busy with other stuff but should be done at some point

**Comment by bukka** [comment]
This has been fixed and the extension compiles and works fine on PHP 7
