### ISSUE TITLE
php-jsond/jsond.c:30:10: fatal error: 'ext/standard/php_smart_str.h' file not found #include "ext/standard/php_smart_str.h"

### ISSUE THREAD

**Issue by Daniel-ccx** [bukka/php-jsond#16]
Hi, man
I tried to make jsond in php7.1.12, but failed.

I checked there is no 'ext/standard/php_smart_str.h' but 'ext/standard/php_smart_string.h'.

How can I solve it?
Thanks

**Comment by bukka** [comment]
@Daniel-ccx Sorry for the late reply. Are you still having an issue with this? This should not happen with the latest master or the PHP headers are not properly installed as it should be caught by `phpc/phpc.h`

**Comment by bukka** [comment]
Waiting a month for a reply I'm expecting there no issue so closing.
