### ISSUE TITLE
php 7.1 ubuntu compile error

### ISSUE THREAD

**Issue by mhf-ir** [bukka/php-jsond#18]
/bin/bash /tmp/php-jsond/libtool --mode=compile cc  -I. -I/tmp/php-jsond -DPHP_ATOM_INC -I/tmp/php-jsond/include -I/tmp/php-jsond/main -I/tmp/php-jsond -I/usr/include/php/20160303 -I/usr/include/php/20160303/main -I/usr/include/php/20160303/TSRM -I/usr/include/php/20160303/Zend -I/usr/include/php/20160303/ext -I/usr/include/php/20160303/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/php-jsond/jsond.c -o jsond.lo 
libtool: compile:  cc -I. -I/tmp/php-jsond -DPHP_ATOM_INC -I/tmp/php-jsond/include -I/tmp/php-jsond/main -I/tmp/php-jsond -I/usr/include/php/20160303 -I/usr/include/php/20160303/main -I/usr/include/php/20160303/TSRM -I/usr/include/php/20160303/Zend -I/usr/include/php/20160303/ext -I/usr/include/php/20160303/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/php-jsond/jsond.c  -fPIC -DPIC -o .libs/jsond.o
/tmp/php-jsond/jsond.c:29:23: fatal error: phpc/phpc.h: No such file or directory
compilation terminated.
Makefile:194: recipe for target 'js

**Comment by bukka** [comment]
You need to clone with `--recursive`. See https://github.com/bukka/php-jsond#manual-installation
