### ISSUE TITLE
phpc/phpc.h 文件缺失？

### ISSUE THREAD

**Issue by sleepingwaly** [bukka/php-jsond#19]
/bin/sh /home/php-jsond-master/libtool --mode=compile cc  -I. -I/home/php-jsond-master -DPHP_ATOM_INC -I/home/php-jsond-master/include -I/home/php-jsond-master/main -I/home/php-jsond-master -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/php-jsond-master/jsond.c -o jsond.lo
libtool: compile:  cc -I. -I/home/php-jsond-master -DPHP_ATOM_INC -I/home/php-jsond-master/include -I/home/php-jsond-master/main -I/home/php-jsond-master -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/php-jsond-master/jsond.c  -DDLL_EXPORT -DPIC -o .libs/jsond.o
/home/php-jsond-master/jsond.c:29:23: 致命错误：phpc/phpc.h：No such file or directory
 #include "phpc/phpc.h"

**Comment by bukka** [comment]
See https://github.com/bukka/php-jsond/issues/18#issuecomment-336729921
