### ISSUE TITLE
configure: WARNING: unrecognized options: --enable-jsond-with-json-prefix

### ISSUE THREAD

**Issue by gufei** [bukka/php-jsond#22]
centos 6.6 
php 5.6.39
php-jsond 1.4.0
./configure --enable-jsond-with-json-prefix

configure: WARNING: unrecognized options: --enable-jsond-with-json-prefix

**Comment by jfcherng** [comment]
Somehow it's `--enable-jsond-prefixing`. https://github.com/bukka/php-jsond/pull/21

**Comment by gufei** [comment]
> 正确的选择是`--enable-jsond-prefixing`。[＃21](https://github.com/bukka/php-jsond/pull/21)

thanks
